_target_: srcC.models.CIFAR10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.Adam
#  _target_: srcC.optim.Adam.LCMAdam

  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
#  _target_: srcC.models.components.net.network
#   _target_: srcC.models.components.mobilenetv2.MobileNetV2
#    _target_: srcC.models.components.densenet.DenseNet
#    _target_: srcC.models.components.demo.MobileNetV2
   _target_: srcC.models.components.densenettest.DenseNetParallel
#    _target_: srcC.models.components.resnet18.Resnet18
#  input_size: 784
#  lin1_size: 64
#  lin2_size: 128
#  lin3_size: 64
#  output_size: 10
