wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    code_path: code/srcM/test.py
    python_version: 3.10.7
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1691034389.43544
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.10.7
      5: 0.15.4
      8:
      - 2
      - 3
      - 5
